data:
  seed: 42
  adversarial_attacks: ["FAB", "FAB_eta20", "FAB_eta30"]

checkpoint:
  path: ""

model:
  name: "lcnn"
  parameters:
    frontend_algorithm: ["lfcc"]
    input_channels: 1
  optimizer:
    lr: 0.0001
