data:
  seed: 42
  adversarial_attacks: : []

checkpoint:
  path: ""

model:
  name: "frontend_specrnet"
  parameters:
    input_channels: 1
    frontend_algorithm: ["lfcc"]
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
